PrefectHQ/ControlFlow

src/controlflow/controllers/controller.py
src/controlflow/controllers/messages.py
src/controlflow/llm/completions.py
src/controlflow/llm/formatting.py
src/controlflow/llm/messages.py
src/controlflow/llm/rules.py
src/controlflow/llm/tools.py
src/controlflow/tasks/task.py
src/controlflow/tools/code.py
src/controlflow/tools/filesystem.py
src/controlflow/tools/web.py
tests/llm/test_tools.py

This hides tool call results from agents that didn't make the call. 
For example, if agent 1 delegates agent 2 to read a large document and summarize it, the tool call loading the entire document into agent 2's context shouldn't pollute agent 1.

Make tool calls private by default

---

docs/assets/code.css

The defaults from mintlify don't match our branding super well. This PR adds a bespoke stylesheet mapped from the prefect.io hljs theme to fit a bit better.
| Before | After |
|---|---|
| <img width="793" alt="Screenshot 2024-06-24 at 1 02 37 PM" src="https://github.com/PrefectHQ/ControlFlow/assets/27291717/d3c314e2-b41a-48ad-8940-a9d556dbb126"> | <img width="793" alt="Screenshot 2024-06-24 at 1 02 39 PM" src="https://github.com/PrefectHQ/ControlFlow/assets/27291717/8e377fb2-cb98-452b-b825-45d1c75d75fa"> |
| <img width="793" alt="Screenshot 2024-06-24 at 1 01 53 PM" src="https://github.com/PrefectHQ/ControlFlow/assets/27291717/7d48691a-7759-4219-b0be-4535a1b9f6a1"> | <img width="793" alt="Screenshot 2024-06-24 at 1 02 02 PM" src="https://github.com/PrefectHQ/ControlFlow/assets/27291717/fef …

Enhancement: Code block styling

---

src/controlflow/__init__.py
src/controlflow/agents/agent.py
src/controlflow/llm/models.py
src/controlflow/llm/tools.py
tests/llm/test_tools.py
tests/test_settings.py

Closes #169 
If you import CF and the default model can't be set (usually/probably because you didn't set the API key env var), a friendly warning is logged but the library doesn't crash. It will crash, however, if you try to use an agent without providing a valid model.

Handle missing API key more gracefully

---

src/controlflow/handlers/print_handler.py

`%l` gives 12-hour format with a leading space if H < 10 but doesnt work on windows and some linux
`%I` is the closest platform independent analog but requires some wrangling to give the desired format
closes concern raised in [this](https://github.com/PrefectHQ/ControlFlow/issues/189#issuecomment-2195613805) comment and see similar issue [here](https://github.com/PrefectHQ/marvin/pull/937)
```python
In [1]: import datetime
In [2]: def format_timestamp(timestamp: datetime.datetime) -> str:
...:     local_timestamp = timestamp.astimezone()
...:     return local_timestamp.strftime("%I:%M:%S %p").lstrip("0").rjust(11)
...:
In [3]: format_timestamp(datetime.datetime.fromtimestamp(123456))
Out[3]: ' 4:17:36 AM'
```

platform independent timestamp

---

src/controlflow/tools/tools.py
tests/tools/test_tools.py

Closes #197 
Tool functions must have serializable input args, but we can silently ignore incompatible return annotations

Fix error when serializing bad tool args

---

docs/guides/default-agent.mdx
docs/guides/llms.mdx
src/controlflow/__init__.py
src/controlflow/agents/__init__.py
src/controlflow/agents/agent.py
src/controlflow/defaults.py
src/controlflow/events/history.py
src/controlflow/flows/flow.py
src/controlflow/llm/models.py
src/controlflow/tasks/task.py
src/controlflow/utilities/testing.py
tests/agents/test_agents.py
tests/fixtures/controlflow.py
tests/tasks/test_tasks.py
tests/test_defaults.py
tests/test_settings.py

This moves default locations from root-level variables to attributes of a `defaults` object which can perform validation. The PR updates docs to match. Note this is a breaking change.
```
controlflow.default_model → controlflow.defaults.model
controlflow.default_agent → controlflow.defaults.agent
controlflow.default_history → controlflow.defaults.history
```

move defaults out of root

---

docs/concepts/tasks.mdx
docs/guides/agentic-loop.mdx
docs/guides/execution-modes.mdx
docs/patterns/instructions.mdx
docs/patterns/stopping-tasks-early.mdx
docs/reference/task-decorator.mdx
src/controlflow/agents/agent.py
src/controlflow/flows/flow.py
src/controlflow/orchestration/controller.py
src/controlflow/tasks/task.py
tests/orchestration/test_controller.py
tests/tasks/test_tasks.py

This is a breaking change. `Task.run_once()` is not `Task.run(steps=1)` to consolidate multiple code paths

Change run_once to steps

---

docs/tutorial.mdx
src/controlflow/agents/agent.py
src/controlflow/agents/teams.py
src/controlflow/flows/flow.py
src/controlflow/orchestration/prompt_templates.py
src/controlflow/tasks/task.py
src/controlflow/utilities/testing.py
tests/agents/test_agents.py
tests/flows/test_flows.py
tests/tasks/test_tasks.py

Permits the prompt to be customized for agents/teams/tasks/flows by passing a jinja-templated `prompt` string at init. This allows customization of what details are shared with the agent when compiling each object.

Update prompt customization

---

README.md

Closes #223.
Not sure why tests are failing, but should be unrelated to this change.

Update README.md header image so displays in PyPI

---

pyproject.toml
src/controlflow/agents/agent.py
src/controlflow/orchestration/agent_context.py
src/controlflow/settings.py
src/controlflow/tools/tools.py
tests/test_settings.py
tests/tools/test_lc_tools.py

Ensure LC tools work

---

src/controlflow/agents/__init__.py
src/controlflow/agents/teams.py
src/controlflow/orchestration/agent_context.py
src/controlflow/tasks/task.py
src/controlflow/tools/orchestration.py
src/controlflow/tools/tools.py
tests/agents/test_teams.py
tests/utilities/test_testing.py

Make teams continue an agents turn if it called a non-terminal tool, otherwise go to next agent

Improve basic round robin

---

src/controlflow/agents/agent.py
src/controlflow/flows/graph.py
src/controlflow/tasks/task.py
src/controlflow/utilities/testing.py
src/controlflow/utilities/types.py
tests/agents/test_agents.py
tests/agents/test_teams.py
tests/orchestration/test_agent_context.py
tests/tasks/test_tasks.py
tests/utilities/test_testing.py

Presently IDs are truncated UUIDs. This PR makes ID a stable hash of various identifying parameters, such that multiple tasks created in the same flow should share an ID. This is primarily useful for recovering historical events.

Add stable ID for task/agent/team

---

src/controlflow/__init__.py
src/controlflow/agents/agent.py
src/controlflow/agents/teams.py
src/controlflow/decorators.py
src/controlflow/defaults.py
src/controlflow/events/base.py
src/controlflow/events/history.py
src/controlflow/flows/flow.py
src/controlflow/orchestration/agent_context.py
src/controlflow/orchestration/orchestrator.py
src/controlflow/settings.py
tests/orchestration/test_agent_context.py

Agent-level setting that determines how event history is loaded.
- `ALL`: the entire history, across all agents and tasks, is shown
- `UPSTREAM`: only events that EITHER involve the current agent OR are upstream of the current task in the flow DAG are shown
- `CURRENT_AGENT`: only events from the current agent, across all tasks
- `CURRENT_TASK`: only events from the current task, across all agents
```python
a = Agent(history_visibility='UPSTREAM')
```
This will probably require some finessing to get right. In particular, taking a task result, modifying it, then passing that data to another task could interrupt the upstream chain (the downstream task can't detect the upstream) and we'll probably want a way to "load" extra history. 
**Note: ** `ALL` history is the default, which is …

Add configurable history visibility

---

docs/patterns/tools.mdx
src/controlflow/orchestration/agent_context.py
src/controlflow/orchestration/prompt_templates.py
src/controlflow/orchestration/prompt_templates/tools.md.jinja
src/controlflow/tools/orchestration.py
src/controlflow/tools/talk_to_user.py
src/controlflow/tools/tools.py
tests/orchestration/test_agent_context.py
tests/tools/test_lc_tools.py
tests/tools/test_tools.py

OpenAI has started erroring if a tool description exceeds 1024 characters, which the `talk_to_user` tool does. This PR adds functionality to add long tool instructions to the system prompt, and also raises an error if a tool description exceeds the limit.

Handle long tool descriptions

---

pyproject.toml
src/controlflow/tasks/task.py
tests/agents/test_agents.py
tests/tasks/test_tasks.py
tests/test_settings.py

```python
zip = cf.run('Complete the task', result_type=Annotated[str, 'a 5 digit zip code'])
assert int(zip)
assert len(zip) == 5
```

Add support for Annotated result types on tasks

---

docs/concepts/tasks/running-tasks.mdx
src/controlflow/orchestration/orchestrator.py
src/controlflow/settings.py
src/controlflow/tasks/task.py
src/controlflow/utilities/testing.py
tests/conftest.py
tests/orchestration/test_orchestrator.py
tests/tasks/test_tasks.py
tests/test_run.py
tests/tools/test_lc_tools.py

- task.max_turns can be set to prohibit more than n turns being spent on a task
- orchestrator.max_turns and orchestrator.max_calls_per_turn can be set
- all have configurable defaults

Improve handling of max turns / max turns per call and enforce task.max_turns

---

src/controlflow/orchestration/orchestrator.py
src/controlflow/settings.py
src/controlflow/tasks/task.py
tests/tasks/test_tasks.py

Eager mode and strict mode are no longer necessary; we create flows on-demand intentionally when using cf.run() and eager mode is essentially always used.

Remove unused settings

---

src/controlflow/orchestration/orchestrator.py
src/controlflow/settings.py
src/controlflow/tasks/task.py
tests/conftest.py
tests/tasks/test_tasks.py

It's very appealing to limit the number of turns for attempting a task by setting `Task(max_turns=...)` but unfortunately in practice this isn't straightforward. If a single agent is applied to the task, then it can iterate forever because there is no concept of formally "ending" a turn. On the other hand, we can't use LLM invocations because a turn *usually* requires two invocations - one to use a tool and another to process it. For the moment, enforcing operational limits at the Task level is too complex. We will leave `run()` limits in place.

Remove max turns from task

---

src/controlflow/events/events.py
src/controlflow/orchestration/orchestrator.py
src/controlflow/orchestration/prompt_templates/tasks.jinja
src/controlflow/orchestration/turn_strategies.py
src/controlflow/tasks/task.py
tests/tasks/test_tasks.py

```python
cf.Task(
agents=[a1, a2],
completion_agents=[a2],
)
```

Allow configurable completion agents

---

src/controlflow/tasks/task.py
tests/tasks/test_tasks.py

The classifier was recovering the *serializable* representation of the labels, rather than the actual label objects. For simple cases this didn't matter, but for Pydantic models it meant that classification yielded a dict, not a hydrated model.

Fix issue with classifying complex labels

---

src/controlflow/tasks/task.py
tests/tasks/test_tasks.py

Aliases like `from typing import Dict, List` were not being properly respected as types when they were supplied as the `result_type`

Fix issue with special type aliases

---

docs/concepts/flows.mdx
docs/examples/language-tutor.mdx
docs/guides/default-agent.mdx
src/controlflow/decorators.py
src/controlflow/flows/flow.py
src/controlflow/tasks/task.py
tests/flows/test_flows.py
tests/tasks/test_tasks.py

- can prevent args from becoming context when using `@flow`
- Flow's `agent` param is now `default_agent`

Flow updates: prevent args from becoming part of context

---

src/controlflow/run.py
src/controlflow/tasks/task.py

This is a little-known config that was slightly misnamed.

Change raise_on_error to raise_on_failure

---

src/controlflow/orchestration/orchestrator.py
src/controlflow/tasks/task.py

```python
cf.Task(wait_for_subtasks=False) # this task can be completed even if it has active subtasks
```

Allow parent tasks to optionally wait for subtasks

---

src/controlflow/agents/agent.py
src/controlflow/orchestration/orchestrator.py
src/controlflow/run.py
src/controlflow/tasks/task.py

```python
import controlflow as cf
cf.run("Write a quick paragraph on AI", model_kwargs=dict(max_tokens=100))
```

Allow model_kwargs to be passed to llm API

---

docs/concepts/agents.mdx
src/controlflow/agents/agent.py
src/controlflow/llm/rules.py
tests/agents/test_agents.py

Each LLM provider may have different requirements for how messages are formatted or presented. For example, OpenAI permits system messages to be interspersed between user messages, but Anthropic requires them to be at the beginning of the conversation. ControlFlow uses provider-specific rules to properly compile messages for each agent's API. 
For common providers like OpenAI and Anthropic, LLM rules can be automatically inferred from the agent's model. However, you can use a custom `LLMRules` object to override these rules or provide rules for non-standard providers.
Here is an example of how to tell the agent to use the Anthropic compilation rules with a custom model that can't be automatically inferred:
```python
import controlflow as cf
llm_model = CustomAnthropicModel()
agent = …
```

Add LLM rules for custom or unrecognized models

---

docs/concepts/flows.mdx
src/controlflow/decorators.py
tests/test_decorator.py

Rather than automatically putting all flow args in context, users can now opt-in to this behavior:
```python
import controlflow as cf
@cf.flow(context_kwargs=['x'])
def f(x, y):
```
Closes #341

Make flow context explicit

---

src/controlflow/settings.py

chore: update settings.py

---

src/controlflow/events/message_compiler.py
src/controlflow/llm/rules.py
tests/test_run.py

Was intended for o1 support, since those models dont support system messages, but it turns out they dont support tools either. PR'ing in case useful in the future.

Add compilation flag for removing all system messages

---

.github/ai-labeler.yml
src/controlflow/tasks/task.py
src/controlflow/utilities/general.py

This is a small change that should benefit smaller models like 4o-mini. Currently the result of a task is passed to a single, typed argument called `result` in the success tool. If the argument is a basemodel, then instead we now accept **kwargs corresponding to all of the model fields. It's a small change amounting to essentially "unwrapping" the `{'result': <>}` dict but seems to have impact.

Pass basemodel attributes directly as kwargs

---

src/controlflow/orchestration/orchestrator.py

Attempting to serialize an `Event` entity within a custom `Handler` / `AsyncHandler` would raise an error on `.json()` due to the handler not being serializable - which makes sense, as it is not a pydantic model. 
A handler usually points to a callable python object (or a collection of them) which do not belong  into a serialization context

Orchestrator: exclude `handlers` field from being serialized

---

src/controlflow/llm/rules.py

An issue was raised in Slack that `AzureChatOpenAI` models were failing with a validation error when being added to an LLMRules object. At first I thought this was a simple fix, as the `OpenAIRules` typed its `model` field as `ChatOpenAI`, not `Union[ChatOpenAI, AzureChatOpenAI]`. However, an error is still being raised even after that change which appears to persist in a simple MRE. 
We can resolve it in CF by removing typing on this field (which isn't great, but fine for now). I will open an issue in Pydantic with the MRE to learn more.

Remove model typing due to validation error

---

src/controlflow/agents/agent.py
src/controlflow/events/base.py
src/controlflow/events/events.py
src/controlflow/events/history.py
src/controlflow/events/message_compiler.py
src/controlflow/events/orchestrator_events.py
src/controlflow/handlers/callback_handler.py
src/controlflow/handlers/print_handler.py
src/controlflow/handlers/queue_handler.py
src/controlflow/orchestration/handler.py
src/controlflow/orchestration/orchestrator.py
src/controlflow/settings.py
src/controlflow/stream.py
src/controlflow/tasks/task.py
src/controlflow/tools/tools.py
tests/tools/test_lc_tools.py
tests/utilities/test_testing.py

This pull request includes significant refactoring and improvements to the event handling system in the `controlflow` package. The changes aim to simplify the event model, improve consistency, and enhance the functionality of event handlers.
A primary, tangible benefit of this PR is enhanced PrintHandler output by using the new public event hooks, e.g.:
https://github.com/user-attachments/assets/246fa022-b33b-450a-8370-bff51b0355a8
The following settings/env vars are respected:
```
enable_default_print_handler # default True
default_print_handler_show_completion_tools # default True
default_print_handler_show_completion_tool_results # default False
```
* Removed `ToolCallEvent` and `ToolResultEvent` classes, replacing them with `AgentToolCall` and `ToolResult` respectively in …

Add new event types

---

docs/mint.json
docs/patterns/running-tasks.mdx
docs/patterns/streaming-tasks.mdx
src/controlflow/__init__.py
src/controlflow/agents/agent.py
src/controlflow/events/base.py
src/controlflow/events/events.py
src/controlflow/events/orchestrator_events.py
src/controlflow/events/task_events.py
src/controlflow/flows/flow.py
src/controlflow/orchestration/orchestrator.py
src/controlflow/run.py
src/controlflow/stream.py
src/controlflow/tasks/task.py
tests/test_run.py

This pull request introduces a new streaming feature to the ControlFlow library, allowing for real-time processing of events during task execution. It also includes significant updates to the documentation and several codebase improvements to support this new functionality.
```python
import controlflow as cf
for event, snapshot, delta in cf.run("Write a poem about AI", stream=True):
if event.event == "agent-content":
print(f"Agent wrote: {snapshot}")
elif event.event == "agent-content-delta":
print(delta, end="", flush=True)
```
To automatically filter for common event types, use the stream flags
```python
import controlflow as cf
for event, snapshot, delta in cf.run(
"Write a poem",
stream=cf.Stream.CONTENT | cf.Stream.TOOLS,
):
print(delta if delta else snapshot)
```
* …

Support streaming events

---

pyproject.toml

A bug was introduced in the openai client which affects all CF installs. We had pinned openai under 1.47 to avoid a previous bug, but that's resolved so we can update the pin here. (Not sure why that pin didn't protect from this bug tbh, maybe the version was getting bumped elsewhere silently?)
The bug manifests as: `Client.__init__() got an unexpected keyword argument 'proxies'`
https://github.com/openai/openai-python/issues/1903

Bump openai version

---

src/controlflow/tools/tools.py
tests/tools/test_tools.py

```
weather_tool = cf.tool(
name="get_current_weather",
description="Get the current weather at a location",
parameters={
"type": "object",
"properties": {
"latitude": {
"type": "number",
"description": "The latitude of the location",
},
"longitude": {
"type": "number",
"description": "The longitude of the location",
},
},
"required": ["latitude", "longitude"],
},
fn=get_current_weather,
)
```
> TypeError: controlflow.tools.tools.Tool() got multiple values for keyword argument 'parameters'
1. We now handle custom parameters first, before any description processing
2. Added a safety check `if param.name not in parameters.get("properties", {})` to ensure we only try to add descriptions for parameters that exist in the schema
3. The rest of the function (return value handling, description …

tools: prioritizes explicitly passed parameters over generated ones

---

docs/guides/configure-llms.mdx
pyproject.toml
src/controlflow/llm/models.py
tests/llm/test_models.py

Ollama is already supported manually, as I describe in this discussion item: https://github.com/PrefectHQ/ControlFlow/discussions/379
Here, I make it possible to support Ollama in automatic configurations, e.g., as conveniently as:
```
export CONTROLFLOW_LLM_MODEL=ollama/qwen2.5
```
I updated the docs here:
https://controlflow.ai/guides/configure-llms#automatic-configuration
with a line for Ollama in supported providers for automatic configuration.
I also added a test in `tests/llm/test_models.py`, and accordingly added `langchain-ollama` as an optional tests dependency.
I systematically calqued all these changes by following the occurrences of the already supported provider `groq` in the repository.
Thanks!

Support provider Ollama for automatic configuration.

---

src/controlflow/agents/agent.py
src/controlflow/defaults.py
src/controlflow/llm/models.py
src/controlflow/orchestration/orchestrator.py
src/controlflow/orchestration/prompt_templates.py
src/controlflow/settings.py
src/controlflow/tasks/task.py

o3 doesn't support temperature, so we need to set this to None to avoid passing through an illegal value.

Set temperature to None by default
